Login styles changed
Azordev/art-marketplace pull request #16
Opened 2022-02-08 18:57 UTC by e-azocar

I added the new styles to the Login page, in the `tailwind.config.js` I defined the colors to use in the app as new classnames.

fixes #11 

## Screenshots 
![image](https://user-images.githubusercontent.com/61360270/153056339-03a628c3-e392-4580-ba08-102347966b50.png)

2022-02-08 20:58 UTC, Israel-Laguan approved these changes

2022-02-09 12:38 UTC, Katsu08 requested changes
I tested on local and doesn't look like the description? . I was cloned the repo and install dependencies, move to the branch then started it. And when I go to Login, I still see the background red.

2022-02-09 12:38 UTC, Katsu08 commented on tailwind.config.js
> +      terciary: "#11698E",
change please for "tertiary"

2022-02-09 17:54 UTC, Katsu08 approved these changes
It looks good! But I notice that the navbar has not changed. Can you change the navbar button color to blue? To look like the design. Or it is for other issue?

![image](https://user-images.githubusercontent.com/66505715/153260476-97be0b69-1999-4c0a-b8c1-2a2ad7a762a9.png)

2022-02-09 19:02 UTC, Katsu08 approved these changes
I see it good. Thanks!

2022-02-09 19:04 UTC, merged

2022-02-11 11:48 UTC, angelik0828 commented
I see it well!!!