issue #34 - fix/size buttons md
Azordev/art-marketplace pull request #40
Opened 2022-02-22 18:44 UTC by Eghinner

In width 827px
![screenshot-localhost_3000-2022 02 22-14_40_00](https://user-images.githubusercontent.com/71513679/155197615-18518e07-1b1d-4204-8f78-45da6b23de5e.png)
Changes in Slider component are to replace Arrows components for backgroundImage

2022-02-23 18:01 UTC, heliomar-pena approved these changes
I see good the code changes and the visual styles, good job!

@angelik0828 please check and confirm visual styles

Before:
![imagen](https://user-images.githubusercontent.com/66505715/155379324-f7417937-3d00-4e7a-b7bf-4679d6a775b5.png)

Now:
![imagen](https://user-images.githubusercontent.com/66505715/155379366-1c88f611-8483-4a65-8e45-d11069b0b589.png)

2022-02-24 03:07 UTC, Israel-Laguan approved these changes
I like SVG more ;<

2022-02-24 18:45 UTC, Katsu08 requested changes
A change that I notice

2022-02-24 18:45 UTC, Katsu08 commented on src/components/Slider.js
> +        : "center no-repeat #11698E url('https://img.icons8.com/material-rounded/24/FFFFFF/chevron-right.png')"
Please change #FFF for `#F8F1F1`

2022-02-24 21:12 UTC, Eghinner commented on src/components/Slider.js
> +        : "center no-repeat #11698E url('https://img.icons8.com/material-rounded/24/FFFFFF/chevron-right.png')"
change made.

2022-02-25 02:18 UTC, Katsu08 commented on src/components/Slider.js
>          : "center no-repeat #11698E url('https://img.icons8.com/material-rounded/24/FFFFFF/chevron-left.png')"
```suggestion
        : "center no-repeat #11698E url('https://img.icons8.com/material-rounded/24/F8F1F1/chevron-left.png')"
```

2022-02-25 02:19 UTC, Katsu08 commented on src/components/Slider.js
>          : "center no-repeat #11698E url('https://img.icons8.com/material-rounded/24/FFFFFF/chevron-right.png')"
```suggestion
        : "center no-repeat #11698E url('https://img.icons8.com/material-rounded/24/F8F1F1/chevron-right.png')"
```

2022-02-25 02:20 UTC, Katsu08 commented on src/components/Slider.js
> +        : "center no-repeat #11698E url('https://img.icons8.com/material-rounded/24/FFFFFF/chevron-right.png')"
Thanks!

2022-02-25 13:50 UTC, angelik0828 commented
In the view of the categories in the slider, the buttons are very close together, there should be a margin that separates the buttons from the arrows in Resolution 1044, another thing is that the buttons of the slider are a bit small for the size of the button, image attached guide. 
The color of the pressed button is ´#F8F1F1´
![image](https://user-images.githubusercontent.com/4030477/155726191-17ef283a-0c5c-49e6-80ec-6e4eb6d0874c.png)

2022-02-25 16:04 UTC, Eghinner commented
New changes:

- Size of the arrows buttons
- Change active slider button backgroundColor
- Add margin to slick-slider in resolution 1280px or lower
![screenshot-localhost_3000-2022 02 25-11_47_19](https://user-images.githubusercontent.com/71513679/155747538-f6cb68ce-cf69-4d13-a05b-41855dcad213.png)

![screenshot-localhost_3000-2022 02 25-11_48_02](https://user-images.githubusercontent.com/71513679/155747565-e66fbac8-4827-437e-b33d-07dd12f59174.png)

2022-02-25 16:56 UTC, Katsu08 approved these changes
Thanks for the change! Very good work!

2022-02-25 20:20 UTC, angelik0828 approved these changes

2022-02-25 20:22 UTC, angelik0828 commented
I see the change looks good good job @Eghinner

2022-02-25 20:31 UTC, merged