Added and configured linters
Azordev/art-marketplace pull request #72
Opened 2022-03-11 14:55 UTC by e-azocar

### Description

I installed and configures the linters `eslint` to Javascript code and `stylelint` to CSS code, I added the command `npm run lint` or `yarn lint` to verify the correct syntax

fixes #69 

#### Screenshots
![image](https://user-images.githubusercontent.com/61360270/157890497-7ab75505-53cc-460d-9cd1-6b1a83c1ddff.png)

2022-03-11 15:12 UTC, Israel-Laguan commented on .eslintrc.json
> +		"es2021": true
JSON files seem to have 4 spaces indentation? JS files looks to have 2

2022-03-14 15:10 UTC, Katsu08 commented on src/components/Footer.jsx
> +import notLoggedButtons from "./isNotLogged";
Can you add a rule to EsLint to change double quotes for simple quotes in JavaScript code?

2022-03-14 15:10 UTC, Katsu08 requested changes
Please check comments

2022-03-14 19:50 UTC, Katsu08 commented
Please rebase to get the last changes

2022-03-16 13:45 UTC, closed without merging